#!/usr/bin/env python3
"""Write partials/header.html and partials/footer.html into every page.

The site is plain static HTML with no build step, so the header and footer were
duplicated in all six pages — which is how three of them drifted out of sync.
The partials are now the single source of truth: edit them, run this script,
and every page is rewritten identically.

The markup stays inlined in each HTML file rather than injected by JavaScript,
so navigation and footer links remain crawlable and there is no flash of
missing chrome on load.

Usage:  python3 tools/sync-partials.py [--check]
        --check exits non-zero if any page is out of sync (for CI).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGES = ["index.html", "about.html", "products.html",
         "applications.html", "testimonials.html", "contact.html"]

BEGIN = "<!-- @partial {name} — generated by tools/sync-partials.py, do not edit here -->"
END = "<!-- /@partial {name} -->"


def render_header(page):
    src = (ROOT / "partials" / "header.html").read_text().rstrip("\n")

    def mark(m):
        return m.group(1) + (" is-active" if m.group(2) == page else "")

    return re.sub(r'(<a href="([a-z]+\.html)" class="nav-link)\{\{ACTIVE:\2\}\}"',
                  lambda m: mark(m) + '"', src)


def render_footer(page):
    return (ROOT / "partials" / "footer.html").read_text().rstrip("\n")


BLOCKS = [("header", render_header, r'<header data-nav="1".*?</header>'),
          ("footer", render_footer, r'<footer class="site-footer">.*?</footer>')]


def sync(page, check=False):
    path = ROOT / page
    text = original = path.read_text()

    for name, render, pattern in BLOCKS:
        body = render(page)
        block = f"{BEGIN.format(name=name)}\n{body}\n{END.format(name=name)}"
        wrapped = re.compile(
            re.escape(BEGIN.format(name=name)) + r".*?" + re.escape(END.format(name=name)),
            re.S)
        if wrapped.search(text):
            text = wrapped.sub(lambda _: block, text, count=1)
        else:
            bare = re.compile(pattern, re.S)
            if not bare.search(text):
                raise SystemExit(f"{page}: no {name} block found")
            text = bare.sub(lambda _: block, text, count=1)

    if text == original:
        return False
    if not check:
        path.write_text(text)
    return True


def main():
    check = "--check" in sys.argv
    drift = [p for p in PAGES if sync(p, check)]
    if check and drift:
        print("out of sync: " + ", ".join(drift))
        return 1
    print("synced" if not check else "all pages in sync",
          f"({len(PAGES)} pages)" + (f", updated: {', '.join(drift)}" if drift and not check else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
